//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFTCreater.NFT.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFTCreater.NFT.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 NFT图片生成完毕！ 的本地化字符串。
        /// </summary>
        internal static string COLLECTION_CREATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COLLECTION_CREATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个功能是替换所有元数据文件中的图片根URL。
        ///
        ///通常我们在生成了图片之后才会上传IPFS服务器，并从服务器上得到CID，此时图片需要一个新的根URL。
        ///
        ///如果你想要替换所有元数据文件中的图片根URL，请点击是。 的本地化字符串。
        /// </summary>
        internal static string CONFIRM_METADATA_UPDATE {
            get {
                return ResourceManager.GetString("CONFIRM_METADATA_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string DEVELOPED_BY {
            get {
                return ResourceManager.GetString("DEVELOPED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确保所有图片素材的宽高相同！{0} 的本地化字符串。
        /// </summary>
        internal static string DIFFERENT_LAYERS_DIMENSION_ERROR {
            get {
                return ResourceManager.GetString("DIFFERENT_LAYERS_DIMENSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNA {0} already exists!!! 的本地化字符串。
        /// </summary>
        internal static string DUPLICATED_DNA {
            get {
                return ResourceManager.GetString("DUPLICATED_DNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片素材排列组合数无法达到所需生成数量，请减少生成数量，或怎加更多的图片素材！ 的本地化字符串。
        /// </summary>
        internal static string DUPLICATED_DNA_MAX_ATTEMPT_ERROR {
            get {
                return ResourceManager.GetString("DUPLICATED_DNA_MAX_ATTEMPT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的文件夹中含有无效的子文件夹，请确子文件夹名称符合规则。它必须以数字开头，后跟减号，然后是想要的名字。请修复这个并重试!{0} 的本地化字符串。
        /// </summary>
        internal static string INVALID_LAYER_NAMING_ERROR {
            get {
                return ResourceManager.GetString("INVALID_LAYER_NAMING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不存在，请确认文件夹名称正确！ 的本地化字符串。
        /// </summary>
        internal static string INVALID_SETTING_ERROR {
            get {
                return ResourceManager.GetString("INVALID_SETTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 元数据更新成功！ 的本地化字符串。
        /// </summary>
        internal static string METADATA_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("METADATA_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已生成 {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string PROCESSING_COLLECTION_ITEM {
            get {
                return ResourceManager.GetString("PROCESSING_COLLECTION_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了未知错误: {0} 的本地化字符串。
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} address copied! 的本地化字符串。
        /// </summary>
        internal static string WALLET_ADDRESS_COPIED {
            get {
                return ResourceManager.GetString("WALLET_ADDRESS_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} wallet for donations 的本地化字符串。
        /// </summary>
        internal static string WALLET_FOR_DONATION_INFO {
            get {
                return ResourceManager.GetString("WALLET_FOR_DONATION_INFO", resourceCulture);
            }
        }
    }
}
